Test request
Perminand/java-shareit pull request #1
Opened 2024-07-09 12:47 UTC by Perminand

2024-07-09 13:03 UTC, Perminand commented
Тесты в разработке

2024-07-10 07:26 UTC, TomattmanYandex requested changes
Привет, выглядит отлично, за исключением пары мест
и еще бросается в глаза то как залогирован юзер контроллер, и что айтем контроллер отличается от него

Плюс по логам,  на контроллере обычно добавляют логи про то что сам запрос случился, на сервисах уже больше информации, например при отлавливании ошибок, или какие данные вернулись

2024-07-10 07:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    Long id;
модификаторы доступа

2024-07-10 07:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    Long id;
модификаторы доступа

2024-07-11 10:01 UTC, TomattmanYandex approved these changes
Принято

2024-07-12 13:05 UTC, merged